# Generated by Django 3.2.25 on 2024-06-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_otpverification_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='is_verified',
        ),
    ]
